<?php
$title = 'Deletar Loja';
$this->headTitle($title);
?>
<h1> <?php echo $this->escapeHtml($title); ?> </h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($loja->getTitle()); ?>' by
    '<?php echo $this->escapeHtml($loja->getAddress()); ?>'?
</p>

<?php
$url = $this->url('loja', array(
'action' => 'delete',
 'id' => $id,
));
?>

<form action='<?php echo $url; ?>' method='post'>
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $loja->getId(); ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>