<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums - INDEX';
$this->headTitle($title);

//Example $_SESSION Usage.
//echo $_SESSION['post_supply']['ex'];
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action' => 'add')); ?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Titulo</th>
        <th>Loja</th>
        <th>Artista</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->getTitle()); ?></td>
            <td><?php echo $this->escapeHtml($album->getLojaid()->getTitle()); ?></td>
            <td><?php echo $this->escapeHtml($album->getArtist()); ?></td>
            <td>
                <a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->getId()));
    ?>">Edit</a>
                <a href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->getId()));
    ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>